---
- name: Trigger kickstarter 
  hosts: vm_host
  vars_files:
    - vars.yml
  tasks:
    - name: Create instance dirs
      ansible.builtin.file:
        path: "{{ playbook_dir }}/rhel4edge/{{ item }}"
        state: directory
        recurse: true
      loop: "{{ rhel4edge_instances }}"

    - name: Trigger kickstart template
      ansible.builtin.template:
        src: kickstart.j2
        dest: "{{ playbook_dir }}/rhel4edge/{{ item }}/kickstart.ks"
      loop: "{{ rhel4edge_instances }}"

    - name: Embed kickstart on freshly built image
      ansible.builtin.shell: mkksiso {{ playbook_dir }}/rhel4edge/{{ item }}/kickstart.ks {{ playbook_dir }}/rhel4edge/r4e-microshift-installer.x86_64.iso /var/lib/libvirt/images/{{ item }}-r4e-microshift-installer.x86_64.iso
      become: true
      loop: "{{ rhel4edge_instances }}"

    - name: Fire up the virtual machine
      ansible.builtin.shell: virt-install --memory 4096 --vcpus 2 --name {{ item }} --cdrom /var/lib/libvirt/images/{{ item }}-r4e-microshift-installer.x86_64.iso --disk size=20 --os-variant rhel8.5 --virt-type kvm --connect qemu:///system
      become: true
      loop: "{{ rhel4edge_instances }}"

    - name: Wait for VMs to settle
      ansible.builtin.pause:
        seconds: 45