- name: Set up ACM hub cluster
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create managedCluster resource for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'managedCluster.j2', template_vars=dict(cluster_name=item)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Create klusterletAddonConfig for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'klusterletAddonConfig.j2', template_vars=dict(cluster_name=item)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Create klusterletAddonConfig for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'clusterRoleBinding.j2', template_vars=dict(cluster_name=item)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Create project for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'project.j2', template_vars=dict(cluster_name=item)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"      

    - name: Remove created files
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ item }}-import.yml"
        state: absent
      loop: "{{ rhel4edge_instances }}"


    - name: Remove created files
      ansible.builtin.file:
        path: "{{ playbook_dir }}/rhel4edge/{{ item }}"
        state: absent
      loop: "{{ rhel4edge_instances }}"

    - name: Destroy VMs
      community.libvirt.virt:
        name: "{{ item }}"
        state: destroyed      
      loop: "{{ rhel4edge_instances }}"

    - name: Undefine VMs
      community.libvirt.virt:
        name: "{{ item }}"
        command: undefine
      loop: "{{ rhel4edge_instances }}"

    - name: Delete VM images
      ansible.builtin.file: 
        path: /var/lib/libvirt/images/{{ item }}-r4e-microshift-installer.x86_64.iso
        state: absent
      become: true
      loop: "{{ rhel4edge_instances }}"
