- name: Set up ACM hub cluster
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Remove managedCluster resource for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'managedCluster.j2', template_vars=dict(cluster_name=item.cluster_name)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Remove klusterletAddonConfig for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'klusterletAddonConfig.j2', template_vars=dict(cluster_name=item.cluster_name)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Remove klusterletAddonConfig for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'clusterRoleBinding.j2', template_vars=dict(cluster_name=item.cluster_name)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"

    - name: Remove project for managed clusters
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'project.j2', template_vars=dict(cluster_name=item.cluster_name)) }}"
        state: absent
        kubeconfig: "{{ playbook_dir }}/kubeconfig"
      loop: "{{ rhel4edge_instances }}"      

    - name: Remove created files
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ item.cluster_name }}-import.yml"
        state: absent
      loop: "{{ rhel4edge_instances }}"


    - name: Remove created files
      ansible.builtin.file:
        path: "{{ playbook_dir }}/rhel4edge/{{ item.cluster_name }}"
        state: absent
      loop: "{{ rhel4edge_instances }}"

- name: Remove VMs
  hosts: vm_host
  vars_files:
    - vars.yml
  tasks:
    - name: Remove VMs from host
      ansible.builtin.shell: virsh destroy {{ item.cluster_name }} && virsh undefine {{ item.cluster_name }}
      become: true
      loop: "{{ rhel4edge_instances }}"
